### ISSUE TITLE
figcaption type scale contrast is overly dramatic on large screen devices

### ISSUE THREAD

**Issue by mezzoblue** [adactio/resilientwebdesign#10]
figcaption type size on desktop browsers appears to be an intended 26px according to the comment below, but instead renders at a calculated 13px. This is in contrast to a calculated 40px body copy size, 72px h2, and even larger type sizes elsewhere. 

https://github.com/adactio/resilientwebdesign/blob/master/css/styles.css#L270

**Comment by adactio** [comment]
That rule is over-ridden by the rule below it:

    font: caption

At that point, I'm handing over to the OS and saying "here, you handle this." Some OSs handle it better than others. :-/

**Comment by mezzoblue** [comment]
Aha, so it is. Some certainly don't handle it well.
