### ISSUE TITLE
Font size is too large.

### ISSUE THREAD

**Issue by spartanatreyu** [adactio/resilientwebdesign#13]
The font size is so large to the point that it is affecting the book's readability. 

Someone posted a [link to your book on hacker news](https://news.ycombinator.com/item?id=17166497) and the majority of the comment section was talking about font size rather than content. Here's one comment:

> I'm not usually one to complain about free content, but with a fontsize like that it was designed to be read across the street from the web. I couldn't make it through the intro page.

**Comment by adactio** [comment]
You can fork this repo and adjust the CSS to any size you like.
