### ISSUE TITLE
Index link results in redirect to home page rather than Index Page

### ISSUE THREAD

**Issue by 06b** [adactio/resilientwebdesign#15]
When clicking the Index link or (navigating to [/index/](https://resilientwebdesign.com/index/index.html)) below the About the author link results in a 301 Moved Permanently (from service worker) which results in the home page reloading rather than loading the Index section found at https://resilientwebdesign.com/index/index.html

**Comment by adactio** [comment]
Thanks for spotting that! It turns out it's a weird thing with Netlify if you have a directory named "index". I've changed the directory name to "theindex" and that seems to have done the trick!
