### ISSUE TITLE
service worker performs an unsafe fetch() and cache.put()

### ISSUE THREAD

**Issue by wanderview** [adactio/resilientwebdesign#6]
The opportunistic `fetch()` and `cache.put()` in the service worker are a bit unsafe.  I mean the bit after the comment `// Meanwhile fetch a fresh copy from the network.`

This bit of code should ideally be protected by a `waitUntil()`.  The spec allows calling `waitUntil()` asynchronously while `respondWith()` is still unresolved, but its not universally implemented yet.  (Only FF53+ at the moment AFAIK.)

In the meantime you can do something like this:

https://github.com/wanderview/wanderview.github.com/blob/master/sw.js#L85

**Comment by wanderview** [comment]
Oh, @jakearchibald has a polyfill here:

https://github.com/jakearchibald/async-waituntil-polyfill

**Comment by adactio** [comment]
Interesting. So what’s the worst that could happen with the unsafe fetch? Is it that there’s no guarantee it will complete? Or could something more catastrophic happen?

**Comment by wanderview** [comment]
Right, the SW may be killed before it completes.  This can mean you do a bunch of network requests with no benefit here and could lead to inconsistent update behavior of resources.

Unfortunately this kind of unsafe async follow-on work was included in early SW explainers and got copied to a bunch of apps.

**Comment by adactio** [comment]
Ah, I see. Well, in this case it’s not so bad if the request never completes because it’s kind of a nice-to-have update of the cache (although I guess it’s a bit of a waste of the user’s bandwidth).

**Comment by adactio** [comment]
Fixed with commit https://github.com/adactio/resilientwebdesign/commit/1bbfd3a6cb141830c9a999448f6e19609f22f689

**Comment by wanderview** [comment]
Thank you!  Even if its not critical here its nice to have more examples in the wild to point people to and to minimize the cut&paste surface of the problem.
